services:
  - type: web
    name: flowerstore-app
    env: docker
    plan: starter
    buildCommand: "" # Không cần nếu sử dụng Docker Image
    startCommand: "" # Sử dụng command mặc định trong Dockerfile
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://flowerstore-db:3306/flower_store?allowPublicKeyRetrieval=true&useSSL=false
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: yourpassword
      - key: REDIS_HOST
        value: flowerstore-redis
      - key: REDIS_PORT
        value: "6379"
      - key: CLOUDINARY_CLOUD_NAME
        value: your-cloudinary-name
      - key: CLOUDINARY_API_KEY
        value: your-cloudinary-api-key
      - key: CLOUDINARY_API_SECRET
        value: your-cloudinary-api-secret
      - key: JWT_SECRET
        value: your-jwt-secret
      - key: JWT_EXPIRATION
        value: "3600000" # Thời gian hết hạn (ms)
      - key: JWT_REFRESH_EXPIRATION
        value: "86400000" # Thời gian làm mới (ms)
      - key: MAIL_USERNAME
        value: your-mail-username
      - key: MAIL_PASSWORD
        value: your-mail-password
      - key: SPRING_MAIL_HOST
        value: smtp.gmail.com
      - key: SPRING_MAIL_PORT
        value: "587"
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
        value: "true"
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
        value: "true"
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST
        value: smtp.gmail.com
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT
        value: "5000"
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT
        value: "5000"
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT
        value: "5000"

  - type: private_service
    name: flowerstore-db
    env: docker
    dockerImage: mysql:8.0
    plan: starter
    envVars:
      - key: MYSQL_DATABASE
        value: flower_store
      - key: MYSQL_ROOT_PASSWORD
        value: yourpassword

  - type: private_service
    name: flowerstore-redis
    env: docker
    dockerImage: redis:alpine
    plan: starter
