services:
  - type: web
    name: flowerstore-app
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://flowerstore-db:3306/flower_store?allowPublicKeyRetrieval=true&useSSL=false
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: yourpassword
      - key: REDIS_HOST
        value: flowerstore-redis
      - key: REDIS_PORT
        value: "6379"
      - key: CLOUDINARY_CLOUD_NAME
        value: your-cloudinary-name
      - key: CLOUDINARY_API_KEY
        value: your-cloudinary-api-key
      - key: CLOUDINARY_API_SECRET
        value: your-cloudinary-api-secret
      - key: JWT_SECRET
        value: your-jwt-secret
      - key: JWT_EXPIRATION
        value: "3600000" # Thời gian hết hạn JWT
      - key: JWT_REFRESH_EXPIRATION
        value: "86400000" # Thời gian làm mới JWT

  - type: web
    name: flowerstore-db
    env: docker
    plan: starter
    dockerImage: mysql:8.0
    envVars:
      - key: MYSQL_DATABASE
        value: flower_store
      - key: MYSQL_ROOT_PASSWORD
        value: yourpassword

  - type: web
    name: flowerstore-redis
    env: docker
    plan: starter
    dockerImage: redis:alpine
